// flow-typed signature: 0b8b0937aec15a4b86efe9c3b48272cb
// flow-typed version: <<STUB>>/teamspeak_v^0.0.5/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'teamspeak'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'teamspeak' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'teamspeak/es6/enum' {
  declare module.exports: any;
}

declare module 'teamspeak/es6/index' {
  declare module.exports: any;
}

declare module 'teamspeak/es6/utils' {
  declare module.exports: any;
}

declare module 'teamspeak/lib/enum' {
  declare module.exports: any;
}

declare module 'teamspeak/lib/index' {
  declare module.exports: any;
}

declare module 'teamspeak/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'teamspeak/es6/enum.js' {
  declare module.exports: $Exports<'teamspeak/es6/enum'>;
}
declare module 'teamspeak/es6/index.js' {
  declare module.exports: $Exports<'teamspeak/es6/index'>;
}
declare module 'teamspeak/es6/utils.js' {
  declare module.exports: $Exports<'teamspeak/es6/utils'>;
}
declare module 'teamspeak/index' {
  declare module.exports: $Exports<'teamspeak'>;
}
declare module 'teamspeak/index.js' {
  declare module.exports: $Exports<'teamspeak'>;
}
declare module 'teamspeak/lib/enum.js' {
  declare module.exports: $Exports<'teamspeak/lib/enum'>;
}
declare module 'teamspeak/lib/index.js' {
  declare module.exports: $Exports<'teamspeak/lib/index'>;
}
declare module 'teamspeak/lib/utils.js' {
  declare module.exports: $Exports<'teamspeak/lib/utils'>;
}
